frameworkVersion: '4.21.0'
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vboyparty
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: backend
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    MY_DYNAMODB_TABLE: backend-dev-table
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
      - dynamodb:GetItem
    Resource:
      - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MY_DYNAMODB_TABLE}
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  create:
    handler: handlers/createBooking.handler
    events:
      - http:
          path: /
          method: post
  get:
    handler: handlers/getBookingById.handler
    events:
      - http:
          path: /{id}
          method: get

resources:
  Resources:
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MY_DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST