name: Deploy backend (develop)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Deploy with Serverless
        run: |
          echo "SERVERLESS_ACCESS_KEY is set? $(if [ -z "$SERVERLESS_ACCESS_KEY" ]; then echo '❌ NO'; else echo '✅ YES'; fi)"
          cd backend
          npx serverless deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_REGION: us-east-1
