name: Deploy frontend

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{github.ref_name == 'develop' && 'dev' || 'prod'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          cd frontend
          echo "Building with $VITE_API_URL"
          printenv | grep VITE_
          VITE_API_URL=${{ secrets.VITE_API_URL }} npm run build

      - name: Determine env
        id: env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          else
            echo "env=prod" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          npm install -g vercel
          if [ "${{ steps.env.outputs.env }}" == "dev" ]; then
            echo "🚀 Deploying to Development..."
            vercel pull --yes --environment=development --token=$VERCEL_TOKEN
            vercel build --token=$VERCEL_TOKEN
            vercel deploy  --token=$VERCEL_TOKEN --yes
          else
            echo "🚀 Deploying to Production..."
            vercel pull --yes --environment=production --token=$VERCEL_TOKEN
            vercel build --token=$VERCEL_TOKEN
            vercel deploy --prod --token=$VERCEL_TOKEN --yes
          fi
